### ISSUE TITLE
关于 visitor 的一些问题

### ISSUE THREAD

**Issue by xueelf** [cxcn/docsify-waline#2]
在官网中 [公告](https://waline.js.org/migration/client.html#%E9%80%89%E9%A1%B9%E9%87%8D%E5%91%BD%E5%90%8D) 有写到，visitor 已更名为 pageview
而且在开启 coverpage 的情况下，进入页面会因获取不到 visitor 节点而导致 js 报错

**Comment by nopdan** [comment]
coverpage 我测试了一下没啥问题，在没有 docsify-count 的情况下创建一个节点，这个倒是可以做

**Comment by nopdan** [comment]
onlyCover 问题已经修复了

**Comment by xueelf** [comment]
> onlyCover 问题已经修复了

![好耶](https://gchat.qpic.cn/gchatpic_new/2225151531/521380411-2534853825-5651AB5B736AC545A1C2FC3BD8792405/0)
