### ISSUE TITLE
waline notification view page doesn't work for docsify

### ISSUE THREAD

**Issue by eteeqii** [cxcn/docsify-waline#5]
waline notification view page doesn't work for docsify

Steps to reproduce
install latest docsify and integrated with commenting system waline
create a comment for a specific docsify page
the waline admin would receive the notification mail regarding to the new comment
click the view page in the mail to open the specific page(the url contains the anchor for the comment)
What is current behaviour
click the view page would open below url would see 404 error, nothing would show in the browser.
https://docs.xxx.com/#/%232

since %23 is the URL encoded representation of #
manually try again with url https://docs.xxx.com/#/#2 in the browser
it would show the specific page, but it didn't anchor to the comment with id=2

What is the expected behaviour
click the view page and show the page and anchor to the specific comment

maybe need think about rewrite of %23
let waline div anchor works.
Other relevant information
 Bug does still occur when all/other plugins are disabled?

Your OS: MAC OS 13.3.1 (22E261)

Node.js version: FROM node:lts-alpine3.17

npm/yarn version:

Browser version: Chrome is up to date Version 112.0.5615.49 (Official Build) (arm64)

Docsify version: RUN npm install -g docsify-cli@latest

Docsify plugins: waline, https://github.com/nopdan/docsify-waline

**Comment by nopdan** [comment]
你不能锚定评论，https://docs.xxx.com/#/#2 会交给 docsify，他会路由到 `#2.md`，找不到便路由到 index，f12 打开控制台可以看到报错。

**Comment by eteeqii** [comment]
谢谢解答：）

确实是不支持锚定评论
如果评论的 id是2，用下面的url也是无法锚定评论（而且waline全部评论都看不到）
https://docs.xxx.com/#/?id=2


BR/Peter






--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: "单单" ***@***.***>
 

 
 发送时间: 2023-04-13 17:38:51
 

 
 收件人:nopdan/docsify-waline ***@***.***> 

 
 抄送:Peter ***@***.***>,Author ***@***.***> 

 
 主题: Re: [nopdan/docsify-waline] waline notification view page doesn'twork for docsify (Issue #5)
 





 你不能锚定评论，https://docs.xxx.com/#/#2 会交给 docsify，他会路由到 #2.md，找不到便路由到 index，f12 打开控制台可以看到报错。

**Comment by nopdan** [comment]
> 谢谢解答：） 确实是不支持锚定评论 如果评论的 id是2，用下面的url也是无法锚定评论（而且waline全部评论都看不到） https://docs.xxx.com/#/?id=2 BR/Peter
> […](#)
> --------------------------------------------------------------------------------
> ------------------ 原始邮件 ------------------ 发件人: "单单" ***@***.***> 发送时间: 2023-04-13 17:38:51 收件人:nopdan/docsify-waline ***@***.***> 抄送:Peter ***@***.***>,Author ***@***.***> 主题: Re: [nopdan/docsify-waline] waline notification view page doesn'twork for docsify (Issue #5) 你不能锚定评论，https://docs.xxx.com/#/#2 会交给 docsify，他会路由到 #2.md，找不到便路由到 index，f12 打开控制台可以看到报错。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

路由失败导致没有加载 `hook.doneEach`，可以给上游 docsify 提 issue。

目前这个插件传 url 是忽略了 ? 后面的，只会传 `/#/`。

**Comment by eteeqii** [comment]
> 路由失败导致没有加载 `hook.doneEach`

谢谢，已在docsify提issue
https://github.com/docsifyjs/docsify/issues/2019
